// Code generated by "pkgimport -p cookiesstore -i github.com/go-pot/sessions/cookiestore -o cookiestore.go"; DO NOT EDIT.
// Install by "go get -u -v github.com/wzshiming/gotype/cmd/pkgimport";
//go:generate pkgimport -p cookiesstore -i github.com/go-pot/sessions/cookiestore -o cookiestore.go

package cookiesstore

import (
	origin "github.com/go-pot/sessions/cookiestore"
)

// Declaration
var (

	// New returns a new CookieStore.
	New = origin.New
)
