// Code generated by "pkgimport -p filesystemstore -i github.com/go-pot/sessions/filesystemstore -o filesystemstore.go"; DO NOT EDIT.
// Install by "go get -u -v github.com/wzshiming/gotype/cmd/pkgimport";
//go:generate pkgimport -p filesystemstore -i github.com/go-pot/sessions/filesystemstore -o filesystemstore.go

package filesystemstore

import (
	origin "github.com/go-pot/sessions/filesystemstore"
)

// Declaration
var (

	// New returns a new FilesystemStore.
	New = origin.New
)
